INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'D', 'DIVORCED', 1, 'DIVORCED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'M', 'MARRIED', 2, 'MARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'S', 'SEPARATED', 3, 'SEPARATED', '2021/07/14', '2021/07/14');
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'U', 'UNMARRIED', 4, 'UNMARRIED', null, null);
INSERT INTO cishfid.marital_status_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, mrtl_stts_src_tp_cd, mrtl_stts_src_tp_desc, mrtl_stts_entps_tp_cd, mrtl_stts_tp_desc, eff_dte, exp_dte) VALUES (nextval('cishfid.marital_status_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = MST)', 'MARITAL STATUS', 'W', 'WIDOWED', 5, 'WIDOWED', null, null);