INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN/INDIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 15, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'OTHER', 5, 'OTHER');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 80, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 45, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 55, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 25, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 81, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 56, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 82, 77004, 'CUSTOMER USER DESCRIPTION PCD
(DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 65, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 0, 'WHITE', 1, 'WHITE');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 65, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 1, 'ASIAN', 2, 'ASIAN');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 65, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 2, 'COLOURED', 3, 'COLOURED');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 65, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 3, 'BLACK', 4, 'BLACK');
INSERT INTO cishfid.ethnic_group_type (id,stm_tp_cd, cmpny_tp_cd, src_tbl_no, src_tbl_nme, src_cat, ethnic_grp_src_tp_cd, ethnic_grp_src_tp_desc, ethnic_grp_entps_tp_cd, ethnic_grp_tp_desc) VALUES (nextval('cishfid.ethnic_group_type_id_seq'),'CIS', 65, 77004, 'CUSTOMER USER DESCRIPTION PCD (DIMENSION-ID = ETH)', 'ETHNIC GROUP', 4, 'UNKNOWN', 6, 'UNKNOWN');